name: Automated API tests using Postman CLI

on: push

defaults:
  run:
    working-directory: ./server

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Install dependencies
        run: npm ci
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
      # run: |
      #   npm run start & postman collection run "17592122-7270d36f-da6d-463b-b4e8-494cac4e21b4"
        run: |
          npm run start & node test.js
